/**
 * components/tasks/TaskStepsSheet.tsx
 * ─────────────────────────────────────────────────────────────────────────────
 * The checklist panel for a single task.
 *
 * A slide-over (not a dialog) so the board stays visible behind it. Steps are
 * added manually or generated by the AI copilot, and each toggle is optimistic
 * so checking something off feels instant.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { useCallback, useEffect, useState } from 'react';
import {
  CheckIcon,
  Loader2Icon,
  PlusIcon,
  SparklesIcon,
  Trash2Icon,
} from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet';
import { cn } from '@/lib/utils';
import { useGamification } from '@/hooks/use-gamification';
import { triggerParticleBurst } from '@/components/gamification/ParticleCanvas';
import { XP_REWARDS } from '@/lib/gamification';
import type { Task, TaskStep } from '@/main/ipc/channels';

export interface TaskStepsSheetProps {
  task: Task | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Called after any mutation so the board can refresh its progress badges. */
  onChanged?: () => void;
}

export function TaskStepsSheet({
  task,
  open,
  onOpenChange,
  onChanged,
}: TaskStepsSheetProps) {
  const [steps, setSteps] = useState<TaskStep[]>([]);
  const [draft, setDraft] = useState('');
  const [loading, setLoading] = useState(false);
  const [breakingDown, setBreakingDown] = useState(false);
  const gamification = useGamification();

  const taskId = task?.id ?? null;

  const load = useCallback(async () => {
    if (!taskId) return;
    setLoading(true);
    try {
      const rows = await window.electron.ipc.invoke<TaskStep[]>(
        'tasks:steps-list',
        { taskId },
      );
      setSteps(rows ?? []);
    } catch {
      toast.error('Could not load steps');
    } finally {
      setLoading(false);
    }
  }, [taskId]);

  useEffect(() => {
    if (open && taskId) void load();
  }, [open, taskId, load]);

  const addStep = async () => {
    const title = draft.trim();
    if (!title || !taskId) return;
    setDraft('');
    try {
      const step = await window.electron.ipc.invoke<TaskStep>(
        'tasks:step-add',
        {
          taskId,
          title,
        },
      );
      setSteps((prev) => [...prev, step]);
      onChanged?.();
    } catch {
      toast.error('Could not add step');
    }
  };

  const toggleStep = async (step: TaskStep) => {
    const next = step.done ? 0 : 1;
    if (!step.done) {
      void gamification.awardXp(
        XP_REWARDS.STEP_COMPLETE,
        'step_complete',
        step.id,
      );
    }
    setSteps((prev) =>
      prev.map((s) => (s.id === step.id ? { ...s, done: next } : s)),
    );
    try {
      await window.electron.ipc.invoke('tasks:step-toggle', {
        id: step.id,
        done: !step.done,
      });
      onChanged?.();
    } catch {
      setSteps((prev) =>
        prev.map((s) => (s.id === step.id ? { ...s, done: step.done } : s)),
      );
      toast.error('Could not update step');
    }
  };

  const removeStep = async (step: TaskStep) => {
    setSteps((prev) => prev.filter((s) => s.id !== step.id));
    try {
      await window.electron.ipc.invoke('tasks:step-delete', { id: step.id });
      onChanged?.();
    } catch {
      toast.error('Could not delete step');
      void load();
    }
  };

  const breakDown = async () => {
    if (!taskId) return;
    setBreakingDown(true);
    try {
      const result = await window.electron.ipc.invoke<{
        steps: TaskStep[];
        note: string;
      }>('tasks:breakdown', { taskId });
      setSteps((prev) => [...prev, ...(result.steps ?? [])]);
      toast.success('Task broken down', {
        description: result.note?.slice(0, 140),
      });
      onChanged?.();
    } catch {
      toast.error('Could not break down task', {
        description: 'Check your model settings and try again.',
      });
    } finally {
      setBreakingDown(false);
    }
  };

  const done = steps.filter((s) => s.done).length;
  const pct = steps.length ? Math.round((done / steps.length) * 100) : 0;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="flex w-full flex-col gap-0 p-0 sm:max-w-md"
      >
        <SheetHeader className="border-b border-border/60">
          <SheetTitle className="pr-8">{task?.title ?? 'Task'}</SheetTitle>
          <SheetDescription>
            Break it into small enough pieces that starting is easy.
          </SheetDescription>
        </SheetHeader>

        <div className="flex flex-col gap-3 p-4">
          {/* Progress */}
          <div className="flex items-center gap-3">
            <Progress value={pct} className="h-1.5" />
            <span className="shrink-0 text-[11px] tabular-nums text-muted-foreground">
              {done}/{steps.length}
            </span>
          </div>

          <Button
            size="sm"
            variant="outline"
            className="w-full gap-2"
            onClick={() => void breakDown()}
            disabled={breakingDown || !taskId}
          >
            {breakingDown ? (
              <Loader2Icon className="size-3.5 animate-spin" />
            ) : (
              <SparklesIcon className="size-3.5 text-amber-500" />
            )}
            {steps.length ? 'Add more with AI' : 'Break down with AI'}
          </Button>
        </div>

        {/* Steps */}
        <div className="min-h-0 flex-1 overflow-y-auto px-4 pb-2">
          {loading ? (
            <div className="flex justify-center py-8">
              <Loader2Icon className="size-4 animate-spin text-muted-foreground" />
            </div>
          ) : steps.length === 0 ? (
            <p className="py-8 text-center text-xs text-muted-foreground">
              No steps yet — add one below, or let the AI break it down.
            </p>
          ) : (
            <ul className="flex flex-col gap-1.5">
              {steps.map((step) => (
                <li
                  key={step.id}
                  className="group flex items-start gap-2.5 rounded-md px-1.5 py-1.5 hover:bg-muted/50"
                >
                  <Checkbox
                    checked={step.done === 1}
                    onCheckedChange={() => void toggleStep(step)}
                    onClick={(e) => {
                      if (!step.done) {
                        triggerParticleBurst(e.clientX, e.clientY);
                      }
                    }}
                    className="mt-0.5"
                  />
                  <span
                    className={cn(
                      'flex-1 text-sm leading-snug',
                      step.done === 1 && 'text-muted-foreground line-through',
                    )}
                  >
                    {step.title}
                  </span>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="size-6 shrink-0 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100 hover:text-destructive"
                    onClick={() => void removeStep(step)}
                    aria-label="Delete step"
                  >
                    <Trash2Icon className="size-3" />
                  </Button>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Add */}
        <div className="flex items-center gap-2 border-t border-border/60 p-4">
          <Input
            placeholder="Add a step…"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault();
                void addStep();
              }
            }}
          />
          <Button
            size="icon"
            onClick={() => void addStep()}
            disabled={!draft.trim()}
            aria-label="Add step"
          >
            {steps.length === 0 ? (
              <PlusIcon className="size-4" />
            ) : (
              <CheckIcon className="size-4" />
            )}
          </Button>
        </div>
      </SheetContent>
    </Sheet>
  );
}
